service: spark-challenge-1
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  # httpApi:
  #   authorizers:
  #     customAuthorizer:
  #       type: request
  #       functionName: auth
  iam:
    role:
      statements: ${file(resources/iam/Iam.yml):Iam}
  environment:
    CRYPTOS_TABLE_NAME: ${self:custom.CryptosTable.name}

plugins:
  - serverless-bundle

resources:
  # Tables
  - ${file(resources/tables/Tables.yml)}

functions: ${file(routes/Routes.yml):Routes}

custom:
  scheduleEnabled: true
  stage: ${self:provider.stage}
  CryptosTable:
    name: !Ref CryptosTable
    arn: !GetAtt CryptosTable.Arn